### PR TITLE
view request body if exist file upload

### PR DESCRIPTION
**Pull request by illyar80**

### CODE REVIEW

**Comment by nostop8** [comment]
@illyar80 
Hi! After we show the body field, the `Yii::$app->request->bodyParams` will have not expected value, which will consist actual body as a property with string value. It will also have `url` and `method` properties additionally, which should not be a part of the `bodyParams`, e.g.:

`{"method":"POST","url":"/test","body":"{\r\n  \"a\": \"\",\r\n  \"b\": \"\"\r\n}"}`

So I guess there's no point showing Body field until this problem is resolved. Its probably some setting in the `doc.js` for ajax request parameters. I'm not sure what exactly it should be. If you have time look into this and this issue will be fixed, then I can accept the pull request.

**Comment by illyar80** [comment]
Hi
`if (Yii::$app->request->post('body')) {
            $post = json_decode(Yii::$app->request->post('body'), true);
        } else {
            $post = Yii::$app->request->post();
        }`

**Comment by illyar80** [comment]
Снимок экрана от 2020-06-04 15-42-59

**Comment by nostop8** [comment]
@illyar80 this approach is breaking the consistency, because your code suppose to look as `Yii::$app->request->post()` instead of `Yii::$app->request->post('body')`.
Until this issue is resolved I cannot approve the pull request. You might just use your own repository in composer.json in case this inconsistency is OK for you.

**Comment by illyar80** [comment]
Ok, thank you for your explanation and for the spending time.

**Pull request closed without merging**
